version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - './home-assistant-config:/config'
    restart: always
    network_mode: host

