version: '3'

services:
  node-red:
    user: root:root
    image: "nodered/node-red:latest"
    ports:
      - "1880:1880"
    volumes:
      - "./data/:/data"
    network_mode: host
    restart: always


